### ISSUE TITLE
TypeError parsedQuery.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by atostudios** [prerender/prerender-node#102]
I've recently switched to prerender service to see if it performed better than the self hosted one but I'm getting this;
```
 TypeError: parsedQuery.hasOwnProperty is not a function
   at Function.prerender.shouldShowPrerenderedPage (/app/node_modules/prerender-node/index.js:132:33)
   at module.exports (/app/node_modules/prerender-node/index.js:6:17)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
   at /app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
   at next (/app/node_modules/express/lib/router/index.js:271:10)
   at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
```
### app.js
```
app.use(require('prerender-node').set('prerenderToken', prerenderToken).set('protocol', 'https'));
```

Any ideas where I may be going wrong?

Thanks

**Comment by thoop** [comment]
Hmm, looks like it's failing on the second line here:
```
var parsedQuery = url.parse(req.url, true).query;
if(parsedQuery && parsedQuery.hasOwnProperty('_escaped_fragment_')) isRequestingPrerenderedPage = true;
```

But `parsedQuery` should always be an object. Which version of Node are you using?

**Comment by thoop** [comment]
Looks like it's Node v6: https://github.com/prerender/prerender-node/pull/103

**Comment by atostudios** [comment]
Yeah switching to 5.1.0 removed this issue. Thanks for looking into this.

**Comment by azachar** [comment]
When will you offer support for Node v6?

**Comment by thoop** [comment]
Should work just fine with Node v6. Please open another issue with your version of node and the error you are seeing if you are having issues.

**Comment by azachar** [comment]
I am having exactly the same error as reported here with node 6.3.1 running on ubuntu 14.04

**Comment by thoop** [comment]
Please create a new issue with a copy of your error stack trace and the version of prerender-node you are using since this issue should have been fixed.
