### ISSUE TITLE
TypeError: parsedQuery.hasOwnProperty is not a function 

### ISSUE THREAD

**Issue by gerardogrimaldi** [prerender/prerender-node#123]
TypeError: parsedQuery.hasOwnProperty is not a function
        at Function.prerender.shouldShowPrerenderedPage (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/prerender-node/index.js:130:33)
        at module.exports (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/prerender-node/index.js:6:17)
        at Layer.handle [as handle_request] (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/express/lib/router/index.js:312:13)
        at /Users/gerardo/Documents/GitHub/fwtv-api/node_modules/express/lib/router/index.js:280:7
        at Function.process_params (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/express/lib/router/index.js:330:12)
        at next (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/express/lib/router/index.js:271:10)
        at SendStream.error (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/serve-static/index.js:120:7)
        at emitOne (events.js:96:13)
        at SendStream.emit (events.js:188:7)
        at SendStream.error (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/serve-static/node_modules/send/index.js:245:17)
        at SendStream.onStatError (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/serve-static/node_modules/send/index.js:356:12)
        at next (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/serve-static/node_modules/send/index.js:630:16)
        at onstat (/Users/gerardo/Documents/GitHub/fwtv-api/node_modules/serve-static/node_modules/send/index.js:619:14)
        at FSReqWrap.oncomplete (fs.js:123:15)

i'm using node 6.9.1 in mac os sierra

**Comment by thoop** [comment]
We no longer use `parsedQuery.hasOwnProperty` in the latest version of prerender-node. Please upgrade to a newer version of prerender-node to fix that issue.
